apiVersion: v1
kind: ConfigMap
metadata:
  name: discuit-config
data:
  config.yaml: |-
    siteName: {{ .Values.discuit.siteName }}
    siteDescription: {{ .Values.discuit.siteDescription }}
    emailContact: {{ .Values.discuit.emailContact }}
    twitterURL: {{ .Values.discuit.twitterURL }}
    discordURL: {{ .Values.discuit.discordURL }}
    githubURL: {{ .Values.discuit.githubURL }}
    substackURL: {{ .Values.discuit.substackURL }}

    isDevelopment: {{ .Values.discuit.isDevelopment }}
    hmacSecret: {{ .Values.discuit.hmacSecret }}
    noLogToFile: {{ .Values.discuit.noLogToFile }}
    csrfOff: {{ .Values.discuit.csrfOff }}

    addr: :8080
    sessionCookieName: {{ .Values.discuit.sessionCookieName }}

    # MariaDB configuration:
    dbAddr: {{ .Values.mariadb.host }} # Required
    dbUser: {{ .Values.mariadb.user }} # Required
    dbPassword: {{ .Values.mariadb.passwd }} # Required
    dbName: {{ .Values.mariadb.databaseName }} # Required

    # ReCAPTCHA or hCaptcha secret and site-key:
    captchaSecret: {{ .Values.discuit.captchaSecret }}
    captchaSiteKey: {{ .Values.discuit.captchaSiteKey }}
    disableRateLimits: {{ .Values.discuit.disableRateLimits }}

    # TLS certificate key-pair paths:
    certFile:
    keyFile:

    defaultFeedSort: {{ .Values.discuit.defaultFeedSort }}
    disableForumCreation: {{ .Values.discuit.disableForumCreation }}
    forumCreationReqPoints: {{ .Values.discuit.forumCreationReqPoints }}
    maxForumsPerUser: {{ .Values.discuit.maxForumsPerUser }}
    imagesFolderPath: "images"
     