apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discuit-images
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-cephfs
  volumeMode: Filesystem
